# Generated by Django 4.1.5 on 2023-01-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
